// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ZnL55ZxUUsYxh4ADejaAGW7lSAI5pos',
    appId: '1:661689961719:web:fa6f3110cf5d224e5457f2',
    messagingSenderId: '661689961719',
    projectId: 'hedieaty-5eb5c',
    authDomain: 'hedieaty-5eb5c.firebaseapp.com',
    storageBucket: 'hedieaty-5eb5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALFblvaSlH27kqNQ4yYf0biokV2YyyUNc',
    appId: '1:661689961719:android:2ec5b70380dbf21c5457f2',
    messagingSenderId: '661689961719',
    projectId: 'hedieaty-5eb5c',
    storageBucket: 'hedieaty-5eb5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyKOs8BRaFFV77Z0FVAhmbJSD4niVPVec',
    appId: '1:661689961719:ios:e96d36a4b5a4989b5457f2',
    messagingSenderId: '661689961719',
    projectId: 'hedieaty-5eb5c',
    storageBucket: 'hedieaty-5eb5c.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyKOs8BRaFFV77Z0FVAhmbJSD4niVPVec',
    appId: '1:661689961719:ios:e96d36a4b5a4989b5457f2',
    messagingSenderId: '661689961719',
    projectId: 'hedieaty-5eb5c',
    storageBucket: 'hedieaty-5eb5c.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_ZnL55ZxUUsYxh4ADejaAGW7lSAI5pos',
    appId: '1:661689961719:web:82c9c489b45c244c5457f2',
    messagingSenderId: '661689961719',
    projectId: 'hedieaty-5eb5c',
    authDomain: 'hedieaty-5eb5c.firebaseapp.com',
    storageBucket: 'hedieaty-5eb5c.firebasestorage.app',
  );
}
